IMP: update conda tutorial in dev docs for python 3.8 and qiime 2022.8 #58
qiime2/dev-docs pull request #60
Opened 2022-12-05 18:58 UTC by colinvwood

2022-12-06 20:31 UTC, lizgehret requested changes
This is looking pretty good @colinvwood, but you've still got a couple of 2019.1 instances that need to be replaced with 2022.8 - I'd do another quick search in the `conda-tutorial.rst` file to update the rest of those and then we should be all set here 🙂

2022-12-07 18:20 UTC, colinvwood commented
The issue said only to replace instances of https://conda.anaconda.org/qiime2/label/r2019.1 with https://conda.anaconda.org/qiime2/label/r2022.8, so I didn't think all 2019.1 instances needed changing, but I'll do that now.

2022-12-07 19:49 UTC, lizgehret commented
> The issue said only to replace instances of https://conda.anaconda.org/qiime2/label/r2019.1 with https://conda.anaconda.org/qiime2/label/r2022.8, so I didn't think all 2019.1 instances needed changing, but I'll do that now.

Apologies if that was unclear, thanks @colinvwood!

2022-12-07 19:50 UTC, lizgehret approved these changes

2022-12-07 19:50 UTC, merged